name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran cmake make libblas-dev liblapack-dev libsuitesparse-dev libmpfr-dev libnetcdf-dev libnetcdff-dev
        sudo apt-get install -y libopenmpi-dev openmpi-bin
        sudo apt-get install -y python3-dev python3-numpy

    - name: Build project
      run: make

    - name: Run tests
      run: make test_all

    - name: Install Python dependencies
      run: pip install xarray numpy netCDF4

    - name: Run golden record test
      run: make golden
