name: test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v31.10.6
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build project
      run: nix develop .#default --command make

    - name: Run tests
      run: nix develop .#default --command make test_all
