name: test

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      libneo_ref:
        default: ''

env:
  LIBNEO_REF: ${{ inputs.libneo_ref }}

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran cmake make libnetcdf-dev libnetcdff-dev pkg-config

    - name: Build project
      run: make

    - name: Run tests
      run: make test_all
